efir/urls.py
from django.contrib import admin
from django.urls import path
from efirapp import views
from django.conf.urls import  url
urlpatterns = [
    path('admin/', admin.site.urls),
    path('home',views.home),
    path('record',views.record),
    path('ajax/load-cities/', views.load_cities, name='ajax_load_cities'),
    url('upload/(?P<aadhaar_id>\d+)/(?P<otp>\d+)', views.complain_file),
    path('upload/login', views.complain_login),
    path('track',views.track_login),
    url('track/(?P<fir_id>\d+)',views.status),
    url('search', views.search, name='search'),
    url('status/(?P<fir_id>\d+)/update/$', views.statusupdateview.as_view()),
    url('aadhar/(?P<aadhaar_id>\d+)', views.aadhar),
    path('state',views.statecreate),
    path('city',views.cityview)
]

efirapp/models.py
from django.db import models
TYPE_CHOICES = (
        ('1', 'Received'),
        ('2', 'Registered'),
        ('3','Investigating'),
        ('4','Charge sheet filed')
    )
class Aadhar(models.Model):
    aadhaar_id = models.BigIntegerField(primary_key=True)
    otp = models.BigIntegerField()
    txn_id = models.BigIntegerField()
    name=models.CharField(max_length=200)
    dob=models.CharField(max_length=50)
    gender = models.CharField(max_length=2)
    phone = models.CharField(max_length=10)
    email = models.CharField(max_length=100)
    address = models.CharField(max_length=500)
    def __unicode__(self):

        return '%s %s %s %s %s %s %s %s %s' % (str(self.aadhaar_id), str(self.otp),
                                               str(self.txn_id), self.name, self.dob , self.gender, self.phone, self.email, self.address )


class State(models.Model):
    name = models.CharField(max_length=100)

    def __str__(self):
        return self.name

class City(models.Model):
    state = models.ForeignKey(State, on_delete=models.CASCADE)
    name = models.CharField(max_length=100)

    def __str__(self):
        return self.name

class Complaint(models.Model):
    fir_id =models.AutoField(primary_key=True)
    aadhar_no = models.ForeignKey(Aadhar, on_delete=models.CASCADE)
    state  = models.ForeignKey(State,on_delete=models.SET_NULL, null=True)
    city = models.ForeignKey(City, on_delete=models.SET_NULL, null=True)
    complain = models.TextField(max_length=10000, blank=True)
    recording = models.FileField(blank=True)

    def save(self, *args, **kwargs):
        is_new = self.pk is None
        super(Complaint, self).save(*args, **kwargs)
        if is_new:
            cd = Status(fir_id=self)
            #cd.fir_id = self.pk
            cd.save()

    def __str__(self):
        return str(self.aadhar_no.aadhaar_id)

class Status(models.Model):

    fir_id = models.ForeignKey(Complaint, on_delete=models.CASCADE)
    status = models.CharField(max_length=10,choices=TYPE_CHOICES,default='1')
    comments = models.TextField(max_length=500,blank=True)

templates/aadhar.html
<!DOCTYPE html>
<html lang="en">
<head>
     <meta charset="UTF-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">

<script src="//ajax.googleapis.com/ajax/libs/jquery/1.11.1/jquery.min.js" type="text/javascript"></script>
<link rel="stylesheet" href="//maxcdn.bootstrapcdn.com/bootstrap/3.3.6/css/bootstrap.min.css" integrity="sha384-1q8mTJOASx8j1Au+a5WDVnPi2lkFfwwEAa8hDDdjZlpLegxhjVME1fgjWPGmkzs7" crossorigin="anonymous">
<!-- Optional theme -->
<link rel="stylesheet" href="//maxcdn.bootstrapcdn.com/bootstrap/3.3.6/css/bootstrap-theme.min.css" integrity="sha384-fLW2N01lMqjakBkx3l/M9EahuwpSfeNvV63J5ezn3uZzapT0u7EYsXMjQV+0En5r" crossorigin="anonymous">

<!-- Latest compiled and minified JavaScript -->
<script src="//maxcdn.bootstrapcdn.com/bootstrap/3.3.6/js/bootstrap.min.js" integrity="sha384-0mSbJDEHialfmuBBQP6A4Qrprq5OVfW37PRR3j5ELqxss1yVqOtnepnHVP9aJ7xS" crossorigin="anonymous"></script>

    <title>Aadhar</title>
     <style>
       .corner {
  position: fixed; /* or absolute */
  top: 0%;
  left: 90%;
}

         .home{
              position: fixed; /* or absolute */
             top: 0%;
             left: 85%;
         }
         #xyz{
             /*position: fixed; /* or absolute */
             top: 10%;
             left: 0%;
             max-height:250px;
             overflow:auto;
         }
         body {
    background-image:url(https://housedemocrats.wa.gov/tmp/2012/12/DomeWebsiteBackground2-1024x512.jpg);
    background-repeat:no-repeat;
    background-size:cover;
 }

   </style>
</head>
<body>


  <script src="//cdnjs.cloudflare.com/ajax/libs/underscore.js/1.8.3/underscore-min.js" type="text/javascript"></script>
  <script src="//cdnjs.cloudflare.com/ajax/libs/backbone.js/1.3.3/backbone-min.js" type="text/javascript"></script>
  <script src="//cdnjs.cloudflare.com/ajax/libs/backbone-localstorage.js/1.1.16/backbone.localStorage-min.js" type="text/javascript"></script>

{%  if list %}



 <table class="table table-hover table-bordered" id="xyz">
 <tr>
        <th>Name</th>
        <th>DOB</th>
        <th>Gender</th>
        <th>Ph No.</th>
        <th>Email id</th>
        <th>Address</th>


 </tr>
          <tbody>
          {% for rest in list %}
            <tr>
                <td>{{ rest.name }}</td>
                <td>{{ rest.dob }}</td>
                <td>{{ rest.gender }}</td>
                <td>{{ rest.phone }}</td>
                <td>{{ rest.email }}</td>
                <td>{{ rest.address }}</td>

            </tr>

          </tbody>
</table>

 {% endfor %}
{% else %}
  No inputs.<br>
  {% endif %}
</body>
</html>

templates/city_dropdown_list_options.html
<option value="">---------</option>
{% for city in cities %}
<option value="{{ city.pk }}">{{ city.name }}</option>
{% endfor %}

templates/comp_list.html
<!DOCTYPE html>
<html lang="en">
<head>
         <meta charset="UTF-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">

<script src="//ajax.googleapis.com/ajax/libs/jquery/1.11.1/jquery.min.js" type="text/javascript"></script>
<link rel="stylesheet" href="//maxcdn.bootstrapcdn.com/bootstrap/3.3.6/css/bootstrap.min.css" integrity="sha384-1q8mTJOASx8j1Au+a5WDVnPi2lkFfwwEAa8hDDdjZlpLegxhjVME1fgjWPGmkzs7" crossorigin="anonymous">
<!-- Optional theme -->
<link rel="stylesheet" href="//maxcdn.bootstrapcdn.com/bootstrap/3.3.6/css/bootstrap-theme.min.css" integrity="sha384-fLW2N01lMqjakBkx3l/M9EahuwpSfeNvV63J5ezn3uZzapT0u7EYsXMjQV+0En5r" crossorigin="anonymous">

<!-- Latest compiled and minified JavaScript -->
<script src="//maxcdn.bootstrapcdn.com/bootstrap/3.3.6/js/bootstrap.min.js" integrity="sha384-0mSbJDEHialfmuBBQP6A4Qrprq5OVfW37PRR3j5ELqxss1yVqOtnepnHVP9aJ7xS" crossorigin="anonymous"></script>

    <title>Complaints</title>
     <style>
       .corner {
  position: fixed; /* or absolute */
  top: 0%;
  left: 90%;
}

         .home{
              position: fixed; /* or absolute */
             top: 0%;
             left: 85%;
         }
         #xyz{
             /*position: fixed; /* or absolute */
             top: 10%;
             left: 0%;
             max-height:250px;
             overflow:auto;
         }
          body {
    background-image:url(https://housedemocrats.wa.gov/tmp/2012/12/DomeWebsiteBackground2-1024x512.jpg);
    background-repeat:no-repeat;
    background-size:cover;
 }
   </style>
</head>
<body>
{% load widget_tweaks %}
<nav class="navbar navbar-default">
  <div class="container-fluid">
    <div class="navbar-header">
      <a class="navbar-brand" >e-FIR Portal</a>
    </div>
    <ul class="nav navbar-nav">
      <li class="active"><a href="/home">Home</a></li>
      <li><a href="/upload/login">File FIR</a></li>
      <li><a href="/track">Track FIR</a></li>

    </ul>
  </div>
</nav>
{% block content %}
  <form method="get">
    <div class="well">
      <h4 style="margin-top: 0">Filter</h4>
      <div class="row">
        <div class="form-group col-sm-4 col-md-3">
          {{ filter.form.state.label_tag }}
          {% render_field filter.form.state class="form-control" %}
        </div>
        <div class="form-group col-sm-4 col-md-3">
          {{ filter.form.city.label_tag }}
          {% render_field filter.form.city class="form-control" %}
        </div>
      </div>
      <button type="submit" class="btn btn-primary">
        <span class="glyphicon glyphicon-search"></span> Search
      </button>
    </div>
  </form>

  <table class="table table-bordered">
    <thead>
      <tr>
          <th>Aadhaar id</th>
        <th>Fir id</th>
        <th>State</th>
        <th>City</th>
        <th>Complain</th>
        <th>Recording</th>
          <th>Status</th>
          <th>Comments</th>
          <th>Edit Status</th>
      </tr>
    </thead>
    <tbody>
      {% for user in filter.qs %}
        <tr>
            <td><a href="/aadhar/{{ user.aadhar_no_id }}">{{ user.aadhar_no_id }}</a></td>
          <td>{{ user.fir_id}}</td>
          <td>{{ user.state }}</td>
          <td>{{ user.city }}</td>
          <td>{{ user.complain }}</td>
            <td>{{ user.recording }}</td>
            <td>{{ user.status_set.all.0.get_status_display }}</td>
            <td>{{ user.status_set.all.0.comments }}</td>
        <td><button class="btn btn-warning center-block" onclick="location.href='/status/{{ user.fir_id }}/update';">Edit</button></td>
        </tr>
      {% empty %}
        <tr>
          <td colspan="5">No data</td>
        </tr>
      {% endfor %}
    </tbody>
  </table>
{% endblock %}
</body>
</html>

templates/complaint_list.html
<!DOCTYPE html>
<html lang="en">
<head>
     <meta charset="UTF-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">

<script src="//ajax.googleapis.com/ajax/libs/jquery/1.11.1/jquery.min.js" type="text/javascript"></script>
<link rel="stylesheet" href="//maxcdn.bootstrapcdn.com/bootstrap/3.3.6/css/bootstrap.min.css" integrity="sha384-1q8mTJOASx8j1Au+a5WDVnPi2lkFfwwEAa8hDDdjZlpLegxhjVME1fgjWPGmkzs7" crossorigin="anonymous">
<!-- Optional theme -->
<link rel="stylesheet" href="//maxcdn.bootstrapcdn.com/bootstrap/3.3.6/css/bootstrap-theme.min.css" integrity="sha384-fLW2N01lMqjakBkx3l/M9EahuwpSfeNvV63J5ezn3uZzapT0u7EYsXMjQV+0En5r" crossorigin="anonymous">

<!-- Latest compiled and minified JavaScript -->
<script src="//maxcdn.bootstrapcdn.com/bootstrap/3.3.6/js/bootstrap.min.js" integrity="sha384-0mSbJDEHialfmuBBQP6A4Qrprq5OVfW37PRR3j5ELqxss1yVqOtnepnHVP9aJ7xS" crossorigin="anonymous"></script>

    <title>Inputs</title>
     <style>
         body, html {
    height: 100%;
    background-size:cover;
    background-repeat: no-repeat;
    background-image: url(https://housedemocrats.wa.gov/tmp/2012/12/DomeWebsiteBackground2-1024x512.jpg);
}
       .corner {
  position: fixed; /* or absolute */
  top: 0%;
  left: 90%;
}

         .home{
              position: fixed; /* or absolute */
             top: 0%;
             left: 85%;
         }
         #xyz{
             /*position: fixed; /* or absolute */
             top: 10%;
             left: 0%;
             max-height:250px;
             overflow:auto;
         }
   </style>
</head>
<body>


  <script src="//cdnjs.cloudflare.com/ajax/libs/underscore.js/1.8.3/underscore-min.js" type="text/javascript"></script>
  <script src="//cdnjs.cloudflare.com/ajax/libs/backbone.js/1.3.3/backbone-min.js" type="text/javascript"></script>
  <script src="//cdnjs.cloudflare.com/ajax/libs/backbone-localstorage.js/1.1.16/backbone.localStorage-min.js" type="text/javascript"></script>
<nav class="navbar navbar-default">
  <div class="container-fluid">
    <div class="navbar-header">
      <a class="navbar-brand" >e-FIR Portal</a>
    </div>
    <ul class="nav navbar-nav">
      <li class="active"><a href="/home">Home</a></li>
      <li><a href="/upload/login">File FIR</a></li>
      <li><a href="/track">Track FIR</a></li>

    </ul>
  </div>
</nav>
{%  if list %}



 <table class="table table-hover table-bordered" id="xyz">
 <tr>
        <th>Fir id</th>
        <th>State</th>
        <th>City</th>
        <th>Complain</th>
        <th>Recording</th>
        <th>Status</th>


 </tr>
          <tbody>
          {% for rest in list %}
            <tr>
                <td>{{ rest.fir_id }}</td>
                <td>{{ rest.state }}</td>
                <td>{{ rest.city }}</td>
                <td>{{ rest.complain }}</td>
                <td>{{ rest.recording }}</td>
                <td><button class="btn btn-warning center-block" onclick="location.href='/track/{{ rest.fir_id }}';">Status</button></td>
            </tr>

          {% endfor %}
          </tbody>
</table>
{% else %}
  No inputs.<br>
  {% endif %}
</body>
</html>

templates/complaint_login.html
<!DOCTYPE html>
<html lang="en">
<head>
<link href="//maxcdn.bootstrapcdn.com/bootstrap/3.3.0/css/bootstrap.min.css" rel="stylesheet" id="bootstrap-css">
<script src="//maxcdn.bootstrapcdn.com/bootstrap/3.3.0/js/bootstrap.min.js"></script>
<script src="//code.jquery.com/jquery-1.11.1.min.js"></script>
    <style>
        /*
 * Specific styles of signin component
 */
/*
 * General styles
 */
body, html {
    height: 100%;
    background-size:cover;
    background-repeat: no-repeat;
    background-image: url(https://housedemocrats.wa.gov/tmp/2012/12/DomeWebsiteBackground2-1024x512.jpg);
}

.card-container.card {
    max-width: 350px;
    padding: 40px 40px;
}

.btn {
    font-weight: 700;
    height: 36px;
    -moz-user-select: none;
    -webkit-user-select: none;
    user-select: none;
    cursor: default;
}

/*
 * Card component
 */
.card {
    background-color: #F7F7F7;
    /* just in case there no content*/
    padding: 20px 25px 30px;
    margin: 0 auto 25px;
    margin-top: 50px;
    /* shadows and rounded borders */
    -moz-border-radius: 2px;
    -webkit-border-radius: 2px;
    border-radius: 2px;
    -moz-box-shadow: 0px 2px 2px rgba(0, 0, 0, 0.3);
    -webkit-box-shadow: 0px 2px 2px rgba(0, 0, 0, 0.3);
    box-shadow: 0px 2px 2px rgba(0, 0, 0, 0.3);
}

.profile-img-card {
    width: 96px;
    height: 96px;
    margin: 0 auto 10px;
    display: block;
    -moz-border-radius: 50%;
    -webkit-border-radius: 50%;
    border-radius: 50%;
}

/*
 * Form styles
 */
.profile-name-card {
    font-size: 16px;
    font-weight: bold;
    text-align: center;
    margin: 10px 0 0;
    min-height: 1em;
}

.form-signin #inputEmail,
.form-signin #inputPassword {
    direction: ltr;
    height: 44px;
    font-size: 16px;
}

.form-signin input[type=email],
.form-signin input[type=password],
.form-signin input[type=text],
.form-signin button {
    width: 100%;
    display: block;
    margin-bottom: 10px;
    z-index: 1;
    position: relative;
    -moz-box-sizing: border-box;
    -webkit-box-sizing: border-box;
    box-sizing: border-box;
}

.form-signin .form-control:focus {
    border-color: rgb(104, 145, 162);
    outline: 0;
    -webkit-box-shadow: inset 0 1px 1px rgba(0,0,0,.075),0 0 8px rgb(104, 145, 162);
    box-shadow: inset 0 1px 1px rgba(0,0,0,.075),0 0 8px rgb(104, 145, 162);
}

.btn.btn-signin {
    /*background-color: #4d90fe; */
    background-color: rgb(104, 145, 162);
    /* background-color: linear-gradient(rgb(104, 145, 162), rgb(12, 97, 33));*/
    padding: 0px;
    font-weight: 700;
    font-size: 14px;
    height: 36px;
    -moz-border-radius: 3px;
    -webkit-border-radius: 3px;
    border-radius: 3px;
    border: none;
    -o-transition: all 0.218s;
    -moz-transition: all 0.218s;
    -webkit-transition: all 0.218s;
    transition: all 0.218s;
}

.btn.btn-signin:hover,
.btn.btn-signin:active,
.btn.btn-signin:focus {
    background-color: rgb(12, 97, 33);
}

.forgot-password {
    color: rgb(104, 145, 162);
}

.forgot-password:hover,
.forgot-password:active,
.forgot-password:focus{
    color: rgb(12, 97, 33);
}
    </style>
</head>
<body>
    <meta charset="UTF-8">
    <title>Login</title>
    <nav class="navbar navbar-default">
  <div class="container-fluid">
    <div class="navbar-header">
      <a class="navbar-brand" >e-FIR Portal</a>
    </div>
    <ul class="nav navbar-nav">
      <li class="active"><a href="/home">Home</a></li>
      <li><a href="/upload/login">File FIR</a></li>
      <li><a href="/track">Track FIR</a></li>

    </ul>
  </div>
</nav>
      <div class="container">
        <div class="card card-container">
            <!-- <img class="profile-img-card" src="//lh3.googleusercontent.com/-6V8xOA6M7BA/AAAAAAAAAAI/AAAAAAAAAAA/rzlHcD0KYwo/photo.jpg?sz=120" alt="" /> -->
            <img id="profile-img" class="profile-img-card" src="//ssl.gstatic.com/accounts/ui/avatar_2x.png" />
            <p id="profile-name" class="profile-name-card"></p>
            {% load widget_tweaks %}
            <form class="form-signin" method="post" enctype="multipart/form-data">
                {% csrf_token %}

                {% render_field form.aadhaar_id class="form-control" placeholder=form.aadhaar_id.label %} <br> <br>
                {% render_field form.otp class="form-control" placeholder=form.otp.label %} <br> <br>
                {% render_field form.txn_id class="form-control" placeholder=form.txn_id.label %} <br> <br>
                <button class="btn btn-lg btn-primary btn-block btn-signin" type="submit">Sign in</button>
            </form><!-- /form -->

        </div><!-- /card-container -->
    </div><!-- /container -->


</body>
</html>

templates/complaint_upload.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Upload Complaint</title>
<script src="//ajax.googleapis.com/ajax/libs/jquery/1.11.1/jquery.min.js" type="text/javascript"></script>
<link rel="stylesheet" href="//maxcdn.bootstrapcdn.com/bootstrap/3.3.6/css/bootstrap.min.css" integrity="sha384-1q8mTJOASx8j1Au+a5WDVnPi2lkFfwwEAa8hDDdjZlpLegxhjVME1fgjWPGmkzs7" crossorigin="anonymous">
<!-- Optional theme -->
<link rel="stylesheet" href="//maxcdn.bootstrapcdn.com/bootstrap/3.3.6/css/bootstrap-theme.min.css" integrity="sha384-fLW2N01lMqjakBkx3l/M9EahuwpSfeNvV63J5ezn3uZzapT0u7EYsXMjQV+0En5r" crossorigin="anonymous">

<!-- Latest compiled and minified JavaScript -->
<script src="//maxcdn.bootstrapcdn.com/bootstrap/3.3.6/js/bootstrap.min.js" integrity="sha384-0mSbJDEHialfmuBBQP6A4Qrprq5OVfW37PRR3j5ELqxss1yVqOtnepnHVP9aJ7xS" crossorigin="anonymous"></script>
    <style>
        /*
 * Specific styles of signin component
 */
/*
 * General styles
 */
body, html {
    height: 100%;
    background-size:cover;
    background-repeat: no-repeat;
    background-image: url(https://housedemocrats.wa.gov/tmp/2012/12/DomeWebsiteBackground2-1024x512.jpg);
}

.card-container.card {
    max-width: 350px;
    padding: 40px 40px;
}

.btn {
    font-weight: 700;
    height: 36px;
    -moz-user-select: none;
    -webkit-user-select: none;
    user-select: none;
    cursor: default;
}

/*
 * Card component
 */
.card {
    background-color: #F7F7F7;
    /* just in case there no content*/
    padding: 20px 25px 30px;
    margin: 0 auto 25px;
    margin-top: 5px;
    /* shadows and rounded borders */
    -moz-border-radius: 2px;
    -webkit-border-radius: 2px;
    border-radius: 2px;
    -moz-box-shadow: 0px 2px 2px rgba(0, 0, 0, 0.3);
    -webkit-box-shadow: 0px 2px 2px rgba(0, 0, 0, 0.3);
    box-shadow: 0px 2px 2px rgba(0, 0, 0, 0.3);
}

.profile-img-card {
    width: 96px;
    height: 96px;
    margin: 0 auto 10px;
    display: block;
    -moz-border-radius: 50%;
    -webkit-border-radius: 50%;
    border-radius: 50%;
}

/*
 * Form styles
 */
.profile-name-card {
    font-size: 16px;
    font-weight: bold;
    text-align: center;
    margin: 10px 0 0;
    min-height: 1em;
}

.form-signin #inputEmail,
.form-signin #inputPassword {
    direction: ltr;
    height: 44px;
    font-size: 16px;
}

.form-signin input[type=email],
.form-signin input[type=password],
.form-signin input[type=text],
.form-signin button {
    width: 100%;
    display: block;
    margin-bottom: 10px;
    z-index: 1;
    position: relative;
    -moz-box-sizing: border-box;
    -webkit-box-sizing: border-box;
    box-sizing: border-box;
}

.form-signin .form-control:focus {
    border-color: rgb(104, 145, 162);
    outline: 0;
    -webkit-box-shadow: inset 0 1px 1px rgba(0,0,0,.075),0 0 8px rgb(104, 145, 162);
    box-shadow: inset 0 1px 1px rgba(0,0,0,.075),0 0 8px rgb(104, 145, 162);
}

.btn.btn-signin {
    /*background-color: #4d90fe; */
    background-color: rgb(104, 145, 162);
    /* background-color: linear-gradient(rgb(104, 145, 162), rgb(12, 97, 33));*/
    padding: 0px;
    font-weight: 700;
    font-size: 14px;
    height: 36px;
    -moz-border-radius: 3px;
    -webkit-border-radius: 3px;
    border-radius: 3px;
    border: none;
    -o-transition: all 0.218s;
    -moz-transition: all 0.218s;
    -webkit-transition: all 0.218s;
    transition: all 0.218s;
}

.btn.btn-signin:hover,
.btn.btn-signin:active,
.btn.btn-signin:focus {
    background-color: rgb(12, 97, 33);
}

.forgot-password {
    color: rgb(104, 145, 162);
}

.forgot-password:hover,
.forgot-password:active,
.forgot-password:focus{
    color: rgb(12, 97, 33);
}
    </style>
</head>
<body>
<nav class="navbar navbar-default">
  <div class="container-fluid">
    <div class="navbar-header">
      <a class="navbar-brand" >e-FIR Portal</a>
    </div>
    <ul class="nav navbar-nav">
      <li class="active"><a href="/home">Home</a></li>
      <li><a href="/upload/login">File FIR</a></li>
      <li><a href="/track">Track FIR</a></li>

    </ul>
  </div>
</nav>
<h2>File FIR report</h2>
{% block content %}
    <h4>Record audio/video :<button class="btn btn-warning" onclick="location.href='/record';">Record</button></h4>
<div class="container">
        <div class="card card-container">

            {% load widget_tweaks %}
            <form class="form-signin" method="post" id="complaintForm" data-cities-url="{% url 'ajax_load_cities' %}" novalidate>
                {% csrf_token %}
                State <br>
                {% render_field form.state class="form-control" placeholder=form.state.label %} <br> <br>
                City<br>
                {% render_field form.city class="form-control" placeholder=form.city.label %} <br> <br>
                {% render_field form.complain class="form-control" placeholder=form.complain.label %} <br> <br>
                Recording<br>
                {% render_field form.recording class="form-control" placeholder=form.recording.label %} <br> <br>
                <button class="btn btn-lg btn-primary btn-block btn-signin" type="submit">Submit</button>
            </form><!-- /form -->

        </div><!-- /card-container -->
    </div><!-- /container -->
  <script src="https://code.jquery.com/jquery-3.3.1.min.js"></script>
  <script>
    $("#id_state").change(function () {
      var url = $("#complaintForm").attr("data-cities-url");  // get the url of the `load_cities` view
      var stateId = $(this).val();  // get the selected country ID from the HTML input

      $.ajax({                       // initialize an AJAX request
        url: url,                    // set the url of the request (= localhost:8000/hr/ajax/load-cities/)
        data: {
          'state': stateId       // add the country id to the GET parameters
        },
        success: function (data) {   // `data` is the return of the `load_cities` view function
          $("#id_city").html(data);  // replace the contents of the city input with the data that came from the server
        }
      });

    });
  </script>

{% endblock %}


</body>
</html>

templates/home.html
<!DOCTYPE html>
<html lang="en">
<head>
  <title>WELCOME</title>
  <link rel="shortcut icon" href="favicon.ico" />
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <link rel="stylesheet" href="//maxcdn.bootstrapcdn.com/bootstrap/3.3.6/css/bootstrap.min.css">
  <script src="//ajax.googleapis.com/ajax/libs/jquery/1.12.4/jquery.min.js"></script>
  <script src="//maxcdn.bootstrapcdn.com/bootstrap/3.3.6/js/bootstrap.min.js"></script>
    <style>
        .centered {
  position: fixed; /* or absolute */
  top: 40%;
  left: 30%;
}
body {
    background-image:url(https://housedemocrats.wa.gov/tmp/2012/12/DomeWebsiteBackground2-1024x512.jpg);
    background-repeat:no-repeat;
    background-size:cover;
 }
    </style>
</head>
<body >
<nav class="navbar navbar-default">
  <div class="container-fluid">
    <div class="navbar-header">
      <a class="navbar-brand" >e-FIR Portal</a>
    </div>
    <ul class="nav navbar-nav">
      <li class="active"><a href="/home">Home</a></li>
      <li><a href="/upload/login">File FIR</a></li>
      <li><a href="/track">Track FIR</a></li>

    </ul>
  </div>
</nav>
        <h3 style="color:black;">Welcome to e-FIR filing portal</h3>
        <div id="header" class="centered">
          <p class="lead" style="color:black;">File or track the status of your FIR complaint by just a click!</p>
      <button class="btn btn-warning center-block" onclick="location.href='/upload/login';">File FIR</button><br>
      <button class="btn btn-success center-block" onclick="location.href='/track';">Track FIR</button><br>
    </div>
</body>
</html>